// @no-log

< {%
    request.variables.set("bank-account-id", 4)
%}

POST {{host}}/api/v1/bank-accounts/{{bank-account-id}}/account-holders
Content-Type: application/json

{
    "accountHolderName":"NBA Jam 1996", "dateOfBirth":"1996-06-24"
}
