POST http://localhost:8090/api/v1/bank-accounts
Content-Type: application/json

{
  "accountHolders": [
    {"accountHolderName":"Jefferson Condotta", "dateOfBirth":"1988-06-24"},
    {"accountHolderName":"Maria Julia", "dateOfBirth":"2015-07-14"}
  ]
}
