// @no-log
POST {{host}}/api/v1/bank-accounts
Content-Type: application/json

{
  "accountHolders": [
    {"accountHolderName":"Marcelo D9", "dateOfBirth":"1992-06-24", "emailAddress": "jefferson.condotta@dummy.com"},
    {"accountHolderName":"Condottinha", "dateOfBirth":"1992-06-24", "emailAddress": "condottinha@dummy.com"}
  ]
}
