// @no-log

< {%
    request.variables.set("bank-account-id", "1"),
    request.variables.set("account-holder-id", "1")
%}

GET {{host}}/api/v1/bank-accounts/{{bank-account-id}}/account-holders/{{account-holder-id}}/identity-document